# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11.3
      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run code formatting
      - name: Run Black and isort
        run: |
          black .
          isort .

      # Step 5: Run linting
      - name: Run linting
        run: |
          flake8 .

      # Step 6: Run tests
      - name: Run tests
        run: |
          pytest scripts/tests.py --maxfail=5 --disable-warnings

      # Step 7: Notify deployment to Streamlit Cloud
      - name: Notify deployment to Streamlit Cloud
        if: success()
        run: |
          echo "Pipeline completed. Streamlit Cloud will redeploy the app automatically."
